import org.gradle.api.file.DuplicatesStrategy
import org.gradle.api.tasks.SourceSetContainer

plugins {
    id 'net.fabricmc.fabric-loom'
    id 'maven-publish'
    id "com.modrinth.minotaur"
}

evaluationDependsOn(":common")

def commonProject = project(":common")
def commonSourceSets = commonProject.extensions.getByType(SourceSetContainer)
def commonMain = commonSourceSets.getByName("main")

base {
    archivesName = project.archives_base_name
}

sourceSets {
    main {
        resources.srcDir("../common/src/main/resources")
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation project(":common")

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Uncomment the following line to enable the deprecated Fabric API modules.
    // These are included in the Fabric API production distribution and allow you to update your mod to the latest modules at a later more convenient time.

    // modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"

    api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    implementation("com.terraformersmc:modmenu:${project.modmenu_version}")
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version, "minecraft_version": inputs.properties.minecraft_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

sourcesJar {
    archiveFileName = "ai-diary-${project.mod_version}-fabric-mc${project.minecraft_version}-sources.jar"
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property "archivesName", project.base.archivesName

    from("${rootProject.projectDir}/LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }

    from(commonMain.output)
    dependsOn(commonProject.tasks.named("classes"))

    archiveFileName = "ai-diary-${project.mod_version}-fabric-mc${project.minecraft_version}.jar"
}

// tasks.register("fabricJarName") // removed

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}

import com.modrinth.minotaur.dependencies.ModDependency

modrinth {
    token = System.getenv('MODRINTH_TOKEN')
    projectId = "${project.modrinth_project_id}"
    versionNumber = "v${project.mod_version}-Fabric"
    versionName = "v${project.mod_version}-mc${project.minecraft_version}-fabric"
    uploadFile = jar
    gameVersions = [project.minecraft_version]
    loaders = ['fabric']
    dependencies = [
            new ModDependency('P7dR8mSH', 'required'), // Fabric API
            new ModDependency('9s6osm5g', 'required'), // Cloth Config API
            new ModDependency('mOgUt4GM', 'required') // Modmenu
    ]
}
task printMethods(type: JavaExec) { classpath = sourceSets.client.runtimeClasspath; mainClass = 'me.datsuns.aidiary.ScreenTest' }
