# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=3.1.0
maven_group=me.datsuns.aidiary
archives_base_name=ai-diary
mod_id=aidiary
mod_group_id=me.datsuns.aidiary
mod_name=AI Diary
mod_license=CC0-1.0
mod_authors=datsuns
mod_description=Automatic diary generator by Gemini AI.
minecraft_version_range=[26.1.2]
neo_version=26.1.2.73

# Modrinth
modrinth_project_id = NBv764f5

# Dependencies
fabric_version=0.150.0+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-beta.1
