plugins {
    id 'java-library'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = 'UTF-8'
}

dependencies {
    api 'com.google.code.gson:gson:2.10.1'
    api 'org.slf4j:slf4j-api:2.0.12'
}
